/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ARSpotDistribution {
  'totalDistributed' : bigint,
  'claimCount' : bigint,
  'spotId' : string,
}
export interface CapturedMonster { 'monster' : Monster, 'captureTime' : bigint }
export interface ChatMessage {
  'content' : string,
  'authorName' : string,
  'sender' : Principal,
  'timestamp' : bigint,
}
export interface CoordinatedPoint {
  'latitude' : number,
  'longitude' : number,
  'address' : string,
}
export interface CreatePaymentResponse {
  'checkoutUrl' : string,
  'sessionId' : string,
}
export interface LineItem {
  'priceId' : string,
  'comment' : [] | [string],
  'quantity' : bigint,
}
export interface Monster {
  'name' : string,
  'energyBoost' : bigint,
  'spawnFrequency' : bigint,
}
export interface PaymentCancelResponse {
  'message' : string,
  'sessionId' : string,
}
export interface PaymentSuccessResponse {
  'message' : string,
  'payment' : {
    'status' : string,
    'paymentMethod' : { 'last4' : string, 'brand' : string },
    'currency' : string,
    'amount' : bigint,
  },
}
export interface PlayerProfile {
  'xp' : bigint,
  'nickname' : string,
  'level' : bigint,
  'capturedMonsters' : Array<CapturedMonster>,
  'availableTokens' : bigint,
  'plantedTokens' : bigint,
  'bonusTokens' : bigint,
  'registered' : boolean,
  'energy' : bigint,
}
export interface QMYPurchaseRequest {
  'tokensRequested' : bigint,
  'timestamp' : bigint,
  'buyer' : Principal,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'adminGetPlayerCount' : ActorMethod<[], bigint>,
  'adminResetPlayer' : ActorMethod<[Principal], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'captureMonster' : ActorMethod<[Monster], undefined>,
  'checkout' : ActorMethod<[Array<LineItem>], CreatePaymentResponse>,
  'claimARSpot' : ActorMethod<[string, bigint], undefined>,
  'clearAllMessages' : ActorMethod<[], undefined>,
  'getARSpotDistribution' : ActorMethod<[string], [] | [ARSpotDistribution]>,
  'getAllPlayerProfiles' : ActorMethod<[], Array<[Principal, PlayerProfile]>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [PlayerProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCapturedMonsters' : ActorMethod<[Principal], Array<CapturedMonster>>,
  'getMessages' : ActorMethod<[bigint, bigint], Array<ChatMessage>>,
  'getPlayerState' : ActorMethod<[], [] | [PlayerProfile]>,
  'getTotalMessagesCount' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [PlayerProfile]>,
  'hasClaimedARSpot' : ActorMethod<[string, Principal], boolean>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'initializeMerkleStorePrices' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'paymentCancel' : ActorMethod<[string], PaymentCancelResponse>,
  'paymentSuccess' : ActorMethod<
    [string, string, string],
    PaymentSuccessResponse
  >,
  'plantCoin' : ActorMethod<[CoordinatedPoint], undefined>,
  'qmy_accounts' : ActorMethod<
    [],
    Array<
      {
        'usd_balance' : number,
        'balance_as_of_time' : bigint,
        'pending_balance' : bigint,
        'account' : Principal,
        'confirmed_balance' : bigint,
      }
    >
  >,
  'qmy_cancel_owner_pending_native_trades_buyer' : ActorMethod<
    [Principal],
    { 'trade_id' : string, 'remaining_tokens' : bigint }
  >,
  'qmy_cancel_owner_pending_native_trades_buyerbywallet' : ActorMethod<
    [Principal],
    { 'trade_id' : string, 'remaining_tokens' : bigint }
  >,
  'qmy_cancel_owner_pending_native_trades_seller' : ActorMethod<
    [Principal],
    { 'trade_id' : string, 'remaining_tokens' : bigint }
  >,
  'qmy_cancel_pending_split' : ActorMethod<
    [string],
    { 'remaining_tokens' : bigint }
  >,
  'qmy_cancel_purchase_request' : ActorMethod<
    [],
    { 'tokens_requested' : bigint, 'timestamp' : bigint }
  >,
  'qmy_createOwnedSplitNativeTrade' : ActorMethod<
    [bigint, number],
    {
      'id' : string,
      'status' : { 'pending' : null },
      'seller' : Principal,
      'tokens' : bigint,
      'timestamp' : bigint,
      'buyer' : Principal,
      'price' : number,
    }
  >,
  'qmy_getActiveNativeTrades' : ActorMethod<[Principal], Array<Principal>>,
  'qmy_getAvailableNativeTrades' : ActorMethod<[Principal], Array<Principal>>,
  'qmy_getCreatedNativeTradeHistory' : ActorMethod<
    [Principal],
    Array<Principal>
  >,
  'qmy_getNativeTradeHistory' : ActorMethod<[Principal], Array<Principal>>,
  'qmy_get_pending_requests_by_buyer' : ActorMethod<
    [Principal],
    Array<QMYPurchaseRequest>
  >,
  'qmy_get_pending_requests_by_caller' : ActorMethod<
    [],
    Array<QMYPurchaseRequest>
  >,
  'qmy_get_purchase_request' : ActorMethod<
    [Principal],
    [] | [QMYPurchaseRequest]
  >,
  'qmy_purchaseOwnedNFTOwnedSplitNativeTrade' : ActorMethod<
    [bigint, Principal],
    { 'remaining_tokens' : bigint, 'tokens_purchased' : bigint }
  >,
  'qmy_purchase_identify' : ActorMethod<
    [bigint, Principal],
    { 'tokens_purchased' : bigint }
  >,
  'qmy_purchase_split' : ActorMethod<
    [string, bigint],
    { '_remaining_tokens' : bigint, 'tokens_purchased' : bigint }
  >,
  'qmy_tokens' : ActorMethod<
    [],
    Array<
      {
        'usd_price' : number,
        'name' : string,
        'available_supply' : bigint,
        'symbol' : string,
      }
    >
  >,
  'qmy_update_purchase_request' : ActorMethod<
    [bigint],
    { 'tokens_requested' : bigint, 'timestamp' : bigint }
  >,
  'qmy_view_purchase_request' : ActorMethod<[], [] | [QMYPurchaseRequest]>,
  'qmymylo_distribute_mylo' : ActorMethod<
    [bigint, number, number],
    {
      'distributor_fee' : number,
      'tokens_distributed' : bigint,
      'total_cost_cents' : number,
      'tokens_remaining' : bigint,
    }
  >,
  'qmymylo_distribute_qmy' : ActorMethod<
    [bigint, number, number],
    {
      'distributor_fee' : number,
      'tokens_distributed' : bigint,
      'total_cost_cents' : number,
      'tokens_remaining' : bigint,
    }
  >,
  'registerPlayer' : ActorMethod<[string], undefined>,
  'rescueSingleCoin' : ActorMethod<[string, CoordinatedPoint], undefined>,
  'restoreEnergy' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[PlayerProfile], undefined>,
  'sendMessage' : ActorMethod<[string, string], undefined>,
  'updateXP' : ActorMethod<[bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];