/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ARSpotDistribution {
  'totalDistributed' : bigint,
  'claimCount' : bigint,
  'spotId' : string,
}
export interface CapturedMonster { 'monster' : Monster, 'captureTime' : bigint }
export interface CoordinatedPoint {
  'latitude' : number,
  'longitude' : number,
  'address' : string,
}
export interface CreatePaymentResponse {
  'checkoutUrl' : string,
  'sessionId' : string,
}
export interface LineItem {
  'priceId' : string,
  'comment' : [] | [string],
  'quantity' : bigint,
}
export interface Monster {
  'name' : string,
  'energyBoost' : bigint,
  'spawnFrequency' : bigint,
}
export interface PaymentCancelResponse {
  'message' : string,
  'sessionId' : string,
}
export interface PaymentSuccessResponse {
  'message' : string,
  'payment' : {
    'status' : string,
    'paymentMethod' : { 'last4' : string, 'brand' : string },
    'currency' : string,
    'amount' : bigint,
  },
}
export interface PlayerProfile {
  'xp' : bigint,
  'nickname' : string,
  'level' : bigint,
  'capturedMonsters' : Array<CapturedMonster>,
  'availableTokens' : bigint,
  'plantedTokens' : bigint,
  'bonusTokens' : bigint,
  'registered' : boolean,
  'energy' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'adminGetPlayerCount' : ActorMethod<[], bigint>,
  'adminResetPlayer' : ActorMethod<[Principal], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'captureMonster' : ActorMethod<[Monster], undefined>,
  'checkout' : ActorMethod<[Array<LineItem>], CreatePaymentResponse>,
  'claimARSpot' : ActorMethod<[string, bigint], undefined>,
  'getARSpotDistribution' : ActorMethod<[string], [] | [ARSpotDistribution]>,
  'getAllPlayerProfiles' : ActorMethod<[], Array<[Principal, PlayerProfile]>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [PlayerProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCapturedMonsters' : ActorMethod<[Principal], Array<CapturedMonster>>,
  'getPlayerState' : ActorMethod<[], [] | [PlayerProfile]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [PlayerProfile]>,
  'hasClaimedARSpot' : ActorMethod<[string, Principal], boolean>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'initializeMerkleStorePrices' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'paymentCancel' : ActorMethod<[string], PaymentCancelResponse>,
  'paymentSuccess' : ActorMethod<
    [string, string, string],
    PaymentSuccessResponse
  >,
  'plantCoin' : ActorMethod<[CoordinatedPoint], undefined>,
  'registerPlayer' : ActorMethod<[string], undefined>,
  'rescueSingleCoin' : ActorMethod<[string, CoordinatedPoint], undefined>,
  'restoreEnergy' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[PlayerProfile], undefined>,
  'updateXP' : ActorMethod<[bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];