/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Monster = IDL.Record({
  'name' : IDL.Text,
  'energyBoost' : IDL.Nat,
  'spawnFrequency' : IDL.Nat,
});
export const LineItem = IDL.Record({
  'priceId' : IDL.Text,
  'comment' : IDL.Opt(IDL.Text),
  'quantity' : IDL.Nat,
});
export const CreatePaymentResponse = IDL.Record({
  'checkoutUrl' : IDL.Text,
  'sessionId' : IDL.Text,
});
export const ARSpotDistribution = IDL.Record({
  'totalDistributed' : IDL.Nat,
  'claimCount' : IDL.Nat,
  'spotId' : IDL.Text,
});
export const CapturedMonster = IDL.Record({
  'monster' : Monster,
  'captureTime' : IDL.Int,
});
export const PlayerProfile = IDL.Record({
  'xp' : IDL.Nat,
  'nickname' : IDL.Text,
  'level' : IDL.Nat,
  'capturedMonsters' : IDL.Vec(CapturedMonster),
  'availableTokens' : IDL.Nat,
  'plantedTokens' : IDL.Nat,
  'bonusTokens' : IDL.Nat,
  'registered' : IDL.Bool,
  'energy' : IDL.Nat,
});
export const ChatMessage = IDL.Record({
  'content' : IDL.Text,
  'authorName' : IDL.Text,
  'sender' : IDL.Principal,
  'timestamp' : IDL.Int,
});
export const PaymentCancelResponse = IDL.Record({
  'message' : IDL.Text,
  'sessionId' : IDL.Text,
});
export const PaymentSuccessResponse = IDL.Record({
  'message' : IDL.Text,
  'payment' : IDL.Record({
    'status' : IDL.Text,
    'paymentMethod' : IDL.Record({ 'last4' : IDL.Text, 'brand' : IDL.Text }),
    'currency' : IDL.Text,
    'amount' : IDL.Nat,
  }),
});
export const CoordinatedPoint = IDL.Record({
  'latitude' : IDL.Float64,
  'longitude' : IDL.Float64,
  'address' : IDL.Text,
});
export const QMYPurchaseRequest = IDL.Record({
  'tokensRequested' : IDL.Nat,
  'timestamp' : IDL.Int,
  'buyer' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'adminGetPlayerCount' : IDL.Func([], [IDL.Nat], ['query']),
  'adminResetPlayer' : IDL.Func([IDL.Principal], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'captureMonster' : IDL.Func([Monster], [], []),
  'checkout' : IDL.Func([IDL.Vec(LineItem)], [CreatePaymentResponse], []),
  'claimARSpot' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'clearAllMessages' : IDL.Func([], [], []),
  'getARSpotDistribution' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(ARSpotDistribution)],
      ['query'],
    ),
  'getAllPlayerProfiles' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, PlayerProfile))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(PlayerProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCapturedMonsters' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(CapturedMonster)],
      ['query'],
    ),
  'getMessages' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(ChatMessage)],
      ['query'],
    ),
  'getPlayerState' : IDL.Func([], [IDL.Opt(PlayerProfile)], []),
  'getTotalMessagesCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(PlayerProfile)],
      ['query'],
    ),
  'hasClaimedARSpot' : IDL.Func(
      [IDL.Text, IDL.Principal],
      [IDL.Bool],
      ['query'],
    ),
  'initializeAccessControl' : IDL.Func([], [], []),
  'initializeMerkleStorePrices' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'paymentCancel' : IDL.Func([IDL.Text], [PaymentCancelResponse], []),
  'paymentSuccess' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [PaymentSuccessResponse],
      [],
    ),
  'plantCoin' : IDL.Func([CoordinatedPoint], [], []),
  'qmy_accounts' : IDL.Func(
      [],
      [
        IDL.Vec(
          IDL.Record({
            'usd_balance' : IDL.Float64,
            'balance_as_of_time' : IDL.Int,
            'pending_balance' : IDL.Nat,
            'account' : IDL.Principal,
            'confirmed_balance' : IDL.Nat,
          })
        ),
      ],
      ['query'],
    ),
  'qmy_cancel_owner_pending_native_trades_buyer' : IDL.Func(
      [IDL.Principal],
      [IDL.Record({ 'trade_id' : IDL.Text, 'remaining_tokens' : IDL.Nat })],
      [],
    ),
  'qmy_cancel_owner_pending_native_trades_buyerbywallet' : IDL.Func(
      [IDL.Principal],
      [IDL.Record({ 'trade_id' : IDL.Text, 'remaining_tokens' : IDL.Nat })],
      [],
    ),
  'qmy_cancel_owner_pending_native_trades_seller' : IDL.Func(
      [IDL.Principal],
      [IDL.Record({ 'trade_id' : IDL.Text, 'remaining_tokens' : IDL.Nat })],
      [],
    ),
  'qmy_cancel_pending_split' : IDL.Func(
      [IDL.Text],
      [IDL.Record({ 'remaining_tokens' : IDL.Nat })],
      [],
    ),
  'qmy_cancel_purchase_request' : IDL.Func(
      [],
      [IDL.Record({ 'tokens_requested' : IDL.Nat, 'timestamp' : IDL.Int })],
      [],
    ),
  'qmy_createOwnedSplitNativeTrade' : IDL.Func(
      [IDL.Nat, IDL.Float64],
      [
        IDL.Record({
          'id' : IDL.Text,
          'status' : IDL.Variant({ 'pending' : IDL.Null }),
          'seller' : IDL.Principal,
          'tokens' : IDL.Nat,
          'timestamp' : IDL.Int,
          'buyer' : IDL.Principal,
          'price' : IDL.Float64,
        }),
      ],
      [],
    ),
  'qmy_getActiveNativeTrades' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'qmy_getAvailableNativeTrades' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'qmy_getCreatedNativeTradeHistory' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'qmy_getNativeTradeHistory' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'qmy_get_pending_requests_by_buyer' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(QMYPurchaseRequest)],
      ['query'],
    ),
  'qmy_get_pending_requests_by_caller' : IDL.Func(
      [],
      [IDL.Vec(QMYPurchaseRequest)],
      ['query'],
    ),
  'qmy_get_purchase_request' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(QMYPurchaseRequest)],
      ['query'],
    ),
  'qmy_purchaseOwnedNFTOwnedSplitNativeTrade' : IDL.Func(
      [IDL.Nat, IDL.Principal],
      [
        IDL.Record({
          'remaining_tokens' : IDL.Nat,
          'tokens_purchased' : IDL.Nat,
        }),
      ],
      [],
    ),
  'qmy_purchase_identify' : IDL.Func(
      [IDL.Nat, IDL.Principal],
      [IDL.Record({ 'tokens_purchased' : IDL.Nat })],
      [],
    ),
  'qmy_purchase_split' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [
        IDL.Record({
          '_remaining_tokens' : IDL.Nat,
          'tokens_purchased' : IDL.Nat,
        }),
      ],
      [],
    ),
  'qmy_tokens' : IDL.Func(
      [],
      [
        IDL.Vec(
          IDL.Record({
            'usd_price' : IDL.Float64,
            'name' : IDL.Text,
            'available_supply' : IDL.Nat,
            'symbol' : IDL.Text,
          })
        ),
      ],
      ['query'],
    ),
  'qmy_update_purchase_request' : IDL.Func(
      [IDL.Nat],
      [IDL.Record({ 'tokens_requested' : IDL.Nat, 'timestamp' : IDL.Int })],
      [],
    ),
  'qmy_view_purchase_request' : IDL.Func(
      [],
      [IDL.Opt(QMYPurchaseRequest)],
      ['query'],
    ),
  'qmymylo_distribute_mylo' : IDL.Func(
      [IDL.Nat, IDL.Float64, IDL.Float64],
      [
        IDL.Record({
          'distributor_fee' : IDL.Float64,
          'tokens_distributed' : IDL.Nat,
          'total_cost_cents' : IDL.Float64,
          'tokens_remaining' : IDL.Nat,
        }),
      ],
      [],
    ),
  'qmymylo_distribute_qmy' : IDL.Func(
      [IDL.Nat, IDL.Float64, IDL.Float64],
      [
        IDL.Record({
          'distributor_fee' : IDL.Float64,
          'tokens_distributed' : IDL.Nat,
          'total_cost_cents' : IDL.Float64,
          'tokens_remaining' : IDL.Nat,
        }),
      ],
      [],
    ),
  'registerPlayer' : IDL.Func([IDL.Text], [], []),
  'rescueSingleCoin' : IDL.Func([IDL.Text, CoordinatedPoint], [], []),
  'restoreEnergy' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([PlayerProfile], [], []),
  'sendMessage' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateXP' : IDL.Func([IDL.Int], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Monster = IDL.Record({
    'name' : IDL.Text,
    'energyBoost' : IDL.Nat,
    'spawnFrequency' : IDL.Nat,
  });
  const LineItem = IDL.Record({
    'priceId' : IDL.Text,
    'comment' : IDL.Opt(IDL.Text),
    'quantity' : IDL.Nat,
  });
  const CreatePaymentResponse = IDL.Record({
    'checkoutUrl' : IDL.Text,
    'sessionId' : IDL.Text,
  });
  const ARSpotDistribution = IDL.Record({
    'totalDistributed' : IDL.Nat,
    'claimCount' : IDL.Nat,
    'spotId' : IDL.Text,
  });
  const CapturedMonster = IDL.Record({
    'monster' : Monster,
    'captureTime' : IDL.Int,
  });
  const PlayerProfile = IDL.Record({
    'xp' : IDL.Nat,
    'nickname' : IDL.Text,
    'level' : IDL.Nat,
    'capturedMonsters' : IDL.Vec(CapturedMonster),
    'availableTokens' : IDL.Nat,
    'plantedTokens' : IDL.Nat,
    'bonusTokens' : IDL.Nat,
    'registered' : IDL.Bool,
    'energy' : IDL.Nat,
  });
  const ChatMessage = IDL.Record({
    'content' : IDL.Text,
    'authorName' : IDL.Text,
    'sender' : IDL.Principal,
    'timestamp' : IDL.Int,
  });
  const PaymentCancelResponse = IDL.Record({
    'message' : IDL.Text,
    'sessionId' : IDL.Text,
  });
  const PaymentSuccessResponse = IDL.Record({
    'message' : IDL.Text,
    'payment' : IDL.Record({
      'status' : IDL.Text,
      'paymentMethod' : IDL.Record({ 'last4' : IDL.Text, 'brand' : IDL.Text }),
      'currency' : IDL.Text,
      'amount' : IDL.Nat,
    }),
  });
  const CoordinatedPoint = IDL.Record({
    'latitude' : IDL.Float64,
    'longitude' : IDL.Float64,
    'address' : IDL.Text,
  });
  const QMYPurchaseRequest = IDL.Record({
    'tokensRequested' : IDL.Nat,
    'timestamp' : IDL.Int,
    'buyer' : IDL.Principal,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'adminGetPlayerCount' : IDL.Func([], [IDL.Nat], ['query']),
    'adminResetPlayer' : IDL.Func([IDL.Principal], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'captureMonster' : IDL.Func([Monster], [], []),
    'checkout' : IDL.Func([IDL.Vec(LineItem)], [CreatePaymentResponse], []),
    'claimARSpot' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'clearAllMessages' : IDL.Func([], [], []),
    'getARSpotDistribution' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ARSpotDistribution)],
        ['query'],
      ),
    'getAllPlayerProfiles' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, PlayerProfile))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(PlayerProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCapturedMonsters' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(CapturedMonster)],
        ['query'],
      ),
    'getMessages' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(ChatMessage)],
        ['query'],
      ),
    'getPlayerState' : IDL.Func([], [IDL.Opt(PlayerProfile)], []),
    'getTotalMessagesCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(PlayerProfile)],
        ['query'],
      ),
    'hasClaimedARSpot' : IDL.Func(
        [IDL.Text, IDL.Principal],
        [IDL.Bool],
        ['query'],
      ),
    'initializeAccessControl' : IDL.Func([], [], []),
    'initializeMerkleStorePrices' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'paymentCancel' : IDL.Func([IDL.Text], [PaymentCancelResponse], []),
    'paymentSuccess' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [PaymentSuccessResponse],
        [],
      ),
    'plantCoin' : IDL.Func([CoordinatedPoint], [], []),
    'qmy_accounts' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Record({
              'usd_balance' : IDL.Float64,
              'balance_as_of_time' : IDL.Int,
              'pending_balance' : IDL.Nat,
              'account' : IDL.Principal,
              'confirmed_balance' : IDL.Nat,
            })
          ),
        ],
        ['query'],
      ),
    'qmy_cancel_owner_pending_native_trades_buyer' : IDL.Func(
        [IDL.Principal],
        [IDL.Record({ 'trade_id' : IDL.Text, 'remaining_tokens' : IDL.Nat })],
        [],
      ),
    'qmy_cancel_owner_pending_native_trades_buyerbywallet' : IDL.Func(
        [IDL.Principal],
        [IDL.Record({ 'trade_id' : IDL.Text, 'remaining_tokens' : IDL.Nat })],
        [],
      ),
    'qmy_cancel_owner_pending_native_trades_seller' : IDL.Func(
        [IDL.Principal],
        [IDL.Record({ 'trade_id' : IDL.Text, 'remaining_tokens' : IDL.Nat })],
        [],
      ),
    'qmy_cancel_pending_split' : IDL.Func(
        [IDL.Text],
        [IDL.Record({ 'remaining_tokens' : IDL.Nat })],
        [],
      ),
    'qmy_cancel_purchase_request' : IDL.Func(
        [],
        [IDL.Record({ 'tokens_requested' : IDL.Nat, 'timestamp' : IDL.Int })],
        [],
      ),
    'qmy_createOwnedSplitNativeTrade' : IDL.Func(
        [IDL.Nat, IDL.Float64],
        [
          IDL.Record({
            'id' : IDL.Text,
            'status' : IDL.Variant({ 'pending' : IDL.Null }),
            'seller' : IDL.Principal,
            'tokens' : IDL.Nat,
            'timestamp' : IDL.Int,
            'buyer' : IDL.Principal,
            'price' : IDL.Float64,
          }),
        ],
        [],
      ),
    'qmy_getActiveNativeTrades' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'qmy_getAvailableNativeTrades' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'qmy_getCreatedNativeTradeHistory' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'qmy_getNativeTradeHistory' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'qmy_get_pending_requests_by_buyer' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(QMYPurchaseRequest)],
        ['query'],
      ),
    'qmy_get_pending_requests_by_caller' : IDL.Func(
        [],
        [IDL.Vec(QMYPurchaseRequest)],
        ['query'],
      ),
    'qmy_get_purchase_request' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(QMYPurchaseRequest)],
        ['query'],
      ),
    'qmy_purchaseOwnedNFTOwnedSplitNativeTrade' : IDL.Func(
        [IDL.Nat, IDL.Principal],
        [
          IDL.Record({
            'remaining_tokens' : IDL.Nat,
            'tokens_purchased' : IDL.Nat,
          }),
        ],
        [],
      ),
    'qmy_purchase_identify' : IDL.Func(
        [IDL.Nat, IDL.Principal],
        [IDL.Record({ 'tokens_purchased' : IDL.Nat })],
        [],
      ),
    'qmy_purchase_split' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [
          IDL.Record({
            '_remaining_tokens' : IDL.Nat,
            'tokens_purchased' : IDL.Nat,
          }),
        ],
        [],
      ),
    'qmy_tokens' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Record({
              'usd_price' : IDL.Float64,
              'name' : IDL.Text,
              'available_supply' : IDL.Nat,
              'symbol' : IDL.Text,
            })
          ),
        ],
        ['query'],
      ),
    'qmy_update_purchase_request' : IDL.Func(
        [IDL.Nat],
        [IDL.Record({ 'tokens_requested' : IDL.Nat, 'timestamp' : IDL.Int })],
        [],
      ),
    'qmy_view_purchase_request' : IDL.Func(
        [],
        [IDL.Opt(QMYPurchaseRequest)],
        ['query'],
      ),
    'qmymylo_distribute_mylo' : IDL.Func(
        [IDL.Nat, IDL.Float64, IDL.Float64],
        [
          IDL.Record({
            'distributor_fee' : IDL.Float64,
            'tokens_distributed' : IDL.Nat,
            'total_cost_cents' : IDL.Float64,
            'tokens_remaining' : IDL.Nat,
          }),
        ],
        [],
      ),
    'qmymylo_distribute_qmy' : IDL.Func(
        [IDL.Nat, IDL.Float64, IDL.Float64],
        [
          IDL.Record({
            'distributor_fee' : IDL.Float64,
            'tokens_distributed' : IDL.Nat,
            'total_cost_cents' : IDL.Float64,
            'tokens_remaining' : IDL.Nat,
          }),
        ],
        [],
      ),
    'registerPlayer' : IDL.Func([IDL.Text], [], []),
    'rescueSingleCoin' : IDL.Func([IDL.Text, CoordinatedPoint], [], []),
    'restoreEnergy' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([PlayerProfile], [], []),
    'sendMessage' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateXP' : IDL.Func([IDL.Int], [], []),
  });
};

export const init = ({ IDL }) => { return []; };