/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ARSpotDistribution {
    totalDistributed: bigint;
    claimCount: bigint;
    spotId: string;
}
export interface CoordinatedPoint {
    latitude: number;
    longitude: number;
    address: string;
}
export interface LineItem {
    priceId: string;
    comment?: string;
    quantity: bigint;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface PlayerProfile {
    xp: bigint;
    nickname: string;
    level: bigint;
    capturedMonsters: Array<CapturedMonster>;
    availableTokens: bigint;
    plantedTokens: bigint;
    bonusTokens: bigint;
    registered: boolean;
    energy: bigint;
}
export interface CapturedMonster {
    monster: Monster;
    captureTime: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface PaymentSuccessResponse {
    message: string;
    payment: {
        status: string;
        paymentMethod: {
            last4: string;
            brand: string;
        };
        currency: string;
        amount: bigint;
    };
}
export interface QMYPurchaseRequest {
    tokensRequested: bigint;
    timestamp: bigint;
    buyer: Principal;
}
export interface PaymentCancelResponse {
    message: string;
    sessionId: string;
}
export interface Monster {
    name: string;
    energyBoost: bigint;
    spawnFrequency: bigint;
}
export interface ChatMessage {
    content: string;
    authorName: string;
    sender: Principal;
    timestamp: bigint;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface CreatePaymentResponse {
    checkoutUrl: string;
    sessionId: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_pending {
    pending = "pending"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    adminGetPlayerCount(): Promise<bigint>;
    adminResetPlayer(user: Principal): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    captureMonster(monster: Monster): Promise<void>;
    checkout(items: Array<LineItem>): Promise<CreatePaymentResponse>;
    claimARSpot(spotId: string, qtmAmount: bigint): Promise<void>;
    clearAllMessages(): Promise<void>;
    getARSpotDistribution(spotId: string): Promise<ARSpotDistribution | null>;
    getAllPlayerProfiles(): Promise<Array<[Principal, PlayerProfile]>>;
    getCallerUserProfile(): Promise<PlayerProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCapturedMonsters(user: Principal): Promise<Array<CapturedMonster>>;
    getMessages(limit: bigint, offset: bigint): Promise<Array<ChatMessage>>;
    getPlayerState(): Promise<PlayerProfile | null>;
    getTotalMessagesCount(): Promise<bigint>;
    getUserProfile(user: Principal): Promise<PlayerProfile | null>;
    hasClaimedARSpot(spotId: string, user: Principal): Promise<boolean>;
    initializeAccessControl(): Promise<void>;
    initializeMerkleStorePrices(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    paymentCancel(sessionId: string): Promise<PaymentCancelResponse>;
    paymentSuccess(sessionId: string, accountId: string, caffeineCustomerId: string): Promise<PaymentSuccessResponse>;
    plantCoin(location: CoordinatedPoint): Promise<void>;
    qmy_accounts(): Promise<Array<{
        usd_balance: number;
        balance_as_of_time: bigint;
        pending_balance: bigint;
        account: Principal;
        confirmed_balance: bigint;
    }>>;
    qmy_cancel_owner_pending_native_trades_buyer(_buyer: Principal): Promise<{
        trade_id: string;
        remaining_tokens: bigint;
    }>;
    qmy_cancel_owner_pending_native_trades_buyerbywallet(_buyer: Principal): Promise<{
        trade_id: string;
        remaining_tokens: bigint;
    }>;
    qmy_cancel_owner_pending_native_trades_seller(_seller: Principal): Promise<{
        trade_id: string;
        remaining_tokens: bigint;
    }>;
    qmy_cancel_pending_split(_trade_id: string): Promise<{
        remaining_tokens: bigint;
    }>;
    qmy_cancel_purchase_request(): Promise<{
        tokens_requested: bigint;
        timestamp: bigint;
    }>;
    qmy_createOwnedSplitNativeTrade(_tokens: bigint, _price: number): Promise<{
        id: string;
        status: Variant_pending;
        seller: Principal;
        tokens: bigint;
        timestamp: bigint;
        buyer: Principal;
        price: number;
    }>;
    qmy_getActiveNativeTrades(_account: Principal): Promise<Array<Principal>>;
    qmy_getAvailableNativeTrades(_account: Principal): Promise<Array<Principal>>;
    qmy_getCreatedNativeTradeHistory(_account: Principal): Promise<Array<Principal>>;
    qmy_getNativeTradeHistory(_account: Principal): Promise<Array<Principal>>;
    qmy_get_pending_requests_by_buyer(buyer: Principal): Promise<Array<QMYPurchaseRequest>>;
    qmy_get_pending_requests_by_caller(): Promise<Array<QMYPurchaseRequest>>;
    qmy_get_purchase_request(buyer: Principal): Promise<QMYPurchaseRequest | null>;
    qmy_purchaseOwnedNFTOwnedSplitNativeTrade(_token: bigint, _wallet: Principal): Promise<{
        remaining_tokens: bigint;
        tokens_purchased: bigint;
    }>;
    qmy_purchase_identify(_tokens: bigint, _wallet: Principal): Promise<{
        tokens_purchased: bigint;
    }>;
    qmy_purchase_split(_trade_id: string, _tokens: bigint): Promise<{
        _remaining_tokens: bigint;
        tokens_purchased: bigint;
    }>;
    qmy_tokens(): Promise<Array<{
        usd_price: number;
        name: string;
        available_supply: bigint;
        symbol: string;
    }>>;
    qmy_update_purchase_request(tokens_requested: bigint): Promise<{
        tokens_requested: bigint;
        timestamp: bigint;
    }>;
    qmy_view_purchase_request(): Promise<QMYPurchaseRequest | null>;
    qmymylo_distribute_mylo(_total_tokens: bigint, _token_price_cents: number, _distributor_fee_cents: number): Promise<{
        distributor_fee: number;
        tokens_distributed: bigint;
        total_cost_cents: number;
        tokens_remaining: bigint;
    }>;
    qmymylo_distribute_qmy(_total_tokens: bigint, _token_price_cents: number, _distributor_fee_cents: number): Promise<{
        distributor_fee: number;
        tokens_distributed: bigint;
        total_cost_cents: number;
        tokens_remaining: bigint;
    }>;
    registerPlayer(nickname: string): Promise<void>;
    rescueSingleCoin(coinId: string, playerLocation: CoordinatedPoint): Promise<void>;
    restoreEnergy(): Promise<void>;
    saveCallerUserProfile(profile: PlayerProfile): Promise<void>;
    sendMessage(authorName: string, content: string): Promise<void>;
    updateXP(xpChange: bigint): Promise<void>;
}
import type { ARSpotDistribution as _ARSpotDistribution, LineItem as _LineItem, PlayerProfile as _PlayerProfile, QMYPurchaseRequest as _QMYPurchaseRequest, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async adminGetPlayerCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetPlayerCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetPlayerCount();
            return result;
        }
    }
    async adminResetPlayer(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminResetPlayer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminResetPlayer(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async captureMonster(arg0: Monster): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.captureMonster(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.captureMonster(arg0);
            return result;
        }
    }
    async checkout(arg0: Array<LineItem>): Promise<CreatePaymentResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.checkout(to_candid_vec_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkout(to_candid_vec_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async claimARSpot(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.claimARSpot(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.claimARSpot(arg0, arg1);
            return result;
        }
    }
    async clearAllMessages(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearAllMessages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearAllMessages();
            return result;
        }
    }
    async getARSpotDistribution(arg0: string): Promise<ARSpotDistribution | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getARSpotDistribution(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getARSpotDistribution(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPlayerProfiles(): Promise<Array<[Principal, PlayerProfile]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPlayerProfiles();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPlayerProfiles();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<PlayerProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCapturedMonsters(arg0: Principal): Promise<Array<CapturedMonster>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCapturedMonsters(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCapturedMonsters(arg0);
            return result;
        }
    }
    async getMessages(arg0: bigint, arg1: bigint): Promise<Array<ChatMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessages(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessages(arg0, arg1);
            return result;
        }
    }
    async getPlayerState(): Promise<PlayerProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlayerState();
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlayerState();
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTotalMessagesCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalMessagesCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalMessagesCount();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<PlayerProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async hasClaimedARSpot(arg0: string, arg1: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasClaimedARSpot(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasClaimedARSpot(arg0, arg1);
            return result;
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async initializeMerkleStorePrices(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeMerkleStorePrices();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeMerkleStorePrices();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async paymentCancel(arg0: string): Promise<PaymentCancelResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.paymentCancel(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.paymentCancel(arg0);
            return result;
        }
    }
    async paymentSuccess(arg0: string, arg1: string, arg2: string): Promise<PaymentSuccessResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.paymentSuccess(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.paymentSuccess(arg0, arg1, arg2);
            return result;
        }
    }
    async plantCoin(arg0: CoordinatedPoint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.plantCoin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.plantCoin(arg0);
            return result;
        }
    }
    async qmy_accounts(): Promise<Array<{
        usd_balance: number;
        balance_as_of_time: bigint;
        pending_balance: bigint;
        account: Principal;
        confirmed_balance: bigint;
    }>> {
        if (this.processError) {
            try {
                const result = await this.actor.qmy_accounts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.qmy_accounts();
            return result;
        }
    }
    async qmy_cancel_owner_pending_native_trades_buyer(arg0: Principal): Promise<{
        trade_id: string;
        remaining_tokens: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.qmy_cancel_owner_pending_native_trades_buyer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.qmy_cancel_owner_pending_native_trades_buyer(arg0);
            return result;
        }
    }
    async qmy_cancel_owner_pending_native_trades_buyerbywallet(arg0: Principal): Promise<{
        trade_id: string;
        remaining_tokens: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.qmy_cancel_owner_pending_native_trades_buyerbywallet(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.qmy_cancel_owner_pending_native_trades_buyerbywallet(arg0);
            return result;
        }
    }
    async qmy_cancel_owner_pending_native_trades_seller(arg0: Principal): Promise<{
        trade_id: string;
        remaining_tokens: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.qmy_cancel_owner_pending_native_trades_seller(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.qmy_cancel_owner_pending_native_trades_seller(arg0);
            return result;
        }
    }
    async qmy_cancel_pending_split(arg0: string): Promise<{
        remaining_tokens: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.qmy_cancel_pending_split(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.qmy_cancel_pending_split(arg0);
            return result;
        }
    }
    async qmy_cancel_purchase_request(): Promise<{
        tokens_requested: bigint;
        timestamp: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.qmy_cancel_purchase_request();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.qmy_cancel_purchase_request();
            return result;
        }
    }
    async qmy_createOwnedSplitNativeTrade(arg0: bigint, arg1: number): Promise<{
        id: string;
        status: Variant_pending;
        seller: Principal;
        tokens: bigint;
        timestamp: bigint;
        buyer: Principal;
        price: number;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.qmy_createOwnedSplitNativeTrade(arg0, arg1);
                return from_candid_record_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.qmy_createOwnedSplitNativeTrade(arg0, arg1);
            return from_candid_record_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async qmy_getActiveNativeTrades(arg0: Principal): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.qmy_getActiveNativeTrades(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.qmy_getActiveNativeTrades(arg0);
            return result;
        }
    }
    async qmy_getAvailableNativeTrades(arg0: Principal): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.qmy_getAvailableNativeTrades(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.qmy_getAvailableNativeTrades(arg0);
            return result;
        }
    }
    async qmy_getCreatedNativeTradeHistory(arg0: Principal): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.qmy_getCreatedNativeTradeHistory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.qmy_getCreatedNativeTradeHistory(arg0);
            return result;
        }
    }
    async qmy_getNativeTradeHistory(arg0: Principal): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.qmy_getNativeTradeHistory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.qmy_getNativeTradeHistory(arg0);
            return result;
        }
    }
    async qmy_get_pending_requests_by_buyer(arg0: Principal): Promise<Array<QMYPurchaseRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.qmy_get_pending_requests_by_buyer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.qmy_get_pending_requests_by_buyer(arg0);
            return result;
        }
    }
    async qmy_get_pending_requests_by_caller(): Promise<Array<QMYPurchaseRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.qmy_get_pending_requests_by_caller();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.qmy_get_pending_requests_by_caller();
            return result;
        }
    }
    async qmy_get_purchase_request(arg0: Principal): Promise<QMYPurchaseRequest | null> {
        if (this.processError) {
            try {
                const result = await this.actor.qmy_get_purchase_request(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.qmy_get_purchase_request(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async qmy_purchaseOwnedNFTOwnedSplitNativeTrade(arg0: bigint, arg1: Principal): Promise<{
        remaining_tokens: bigint;
        tokens_purchased: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.qmy_purchaseOwnedNFTOwnedSplitNativeTrade(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.qmy_purchaseOwnedNFTOwnedSplitNativeTrade(arg0, arg1);
            return result;
        }
    }
    async qmy_purchase_identify(arg0: bigint, arg1: Principal): Promise<{
        tokens_purchased: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.qmy_purchase_identify(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.qmy_purchase_identify(arg0, arg1);
            return result;
        }
    }
    async qmy_purchase_split(arg0: string, arg1: bigint): Promise<{
        _remaining_tokens: bigint;
        tokens_purchased: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.qmy_purchase_split(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.qmy_purchase_split(arg0, arg1);
            return result;
        }
    }
    async qmy_tokens(): Promise<Array<{
        usd_price: number;
        name: string;
        available_supply: bigint;
        symbol: string;
    }>> {
        if (this.processError) {
            try {
                const result = await this.actor.qmy_tokens();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.qmy_tokens();
            return result;
        }
    }
    async qmy_update_purchase_request(arg0: bigint): Promise<{
        tokens_requested: bigint;
        timestamp: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.qmy_update_purchase_request(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.qmy_update_purchase_request(arg0);
            return result;
        }
    }
    async qmy_view_purchase_request(): Promise<QMYPurchaseRequest | null> {
        if (this.processError) {
            try {
                const result = await this.actor.qmy_view_purchase_request();
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.qmy_view_purchase_request();
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async qmymylo_distribute_mylo(arg0: bigint, arg1: number, arg2: number): Promise<{
        distributor_fee: number;
        tokens_distributed: bigint;
        total_cost_cents: number;
        tokens_remaining: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.qmymylo_distribute_mylo(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.qmymylo_distribute_mylo(arg0, arg1, arg2);
            return result;
        }
    }
    async qmymylo_distribute_qmy(arg0: bigint, arg1: number, arg2: number): Promise<{
        distributor_fee: number;
        tokens_distributed: bigint;
        total_cost_cents: number;
        tokens_remaining: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.qmymylo_distribute_qmy(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.qmymylo_distribute_qmy(arg0, arg1, arg2);
            return result;
        }
    }
    async registerPlayer(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerPlayer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerPlayer(arg0);
            return result;
        }
    }
    async rescueSingleCoin(arg0: string, arg1: CoordinatedPoint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rescueSingleCoin(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rescueSingleCoin(arg0, arg1);
            return result;
        }
    }
    async restoreEnergy(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.restoreEnergy();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.restoreEnergy();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: PlayerProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async sendMessage(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0, arg1);
            return result;
        }
    }
    async updateXP(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateXP(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateXP(arg0);
            return result;
        }
    }
}
function from_candid_UserRole_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ARSpotDistribution]): ARSpotDistribution | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PlayerProfile]): PlayerProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_QMYPurchaseRequest]): QMYPurchaseRequest | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: {
        pending: null;
    };
    seller: Principal;
    tokens: bigint;
    timestamp: bigint;
    buyer: Principal;
    price: number;
}): {
    id: string;
    status: Variant_pending;
    seller: Principal;
    tokens: bigint;
    timestamp: bigint;
    buyer: Principal;
    price: number;
} {
    return {
        id: value.id,
        status: from_candid_variant_n18(_uploadFile, _downloadFile, value.status),
        seller: value.seller,
        tokens: value.tokens,
        timestamp: value.timestamp,
        buyer: value.buyer,
        price: value.price
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
}): Variant_pending {
    return "pending" in value ? Variant_pending.pending : value;
}
function to_candid_LineItem_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LineItem): _LineItem {
    return to_candid_record_n12(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    priceId: string;
    comment?: string;
    quantity: bigint;
}): {
    priceId: string;
    comment: [] | [string];
    quantity: bigint;
} {
    return {
        priceId: value.priceId,
        comment: value.comment ? candid_some(value.comment) : candid_none(),
        quantity: value.quantity
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<LineItem>): Array<_LineItem> {
    return value.map((x)=>to_candid_LineItem_n11(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
