/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ARSpotClaim {
  'claimTime' : bigint,
  'claimedBy' : Principal,
  'spotId' : string,
  'qtmAmount' : bigint,
}
export interface ARSpotDistribution {
  'totalDistributed' : bigint,
  'claimCount' : bigint,
  'spotId' : string,
}
export interface CapturedMonster { 'monster' : Monster, 'captureTime' : bigint }
export interface ChatMessage {
  'content' : string,
  'authorName' : string,
  'sender' : Principal,
  'timestamp' : bigint,
}
export interface CoordinatedPoint {
  'latitude' : number,
  'longitude' : number,
  'address' : string,
}
export interface DailyLimits {
  'rescuesToday' : bigint,
  'plantsToday' : bigint,
  'lastResetTime' : bigint,
}
export type ExternalBlob = Uint8Array;
export interface MapMarker {
  'id' : string,
  'latitude' : number,
  'description' : string,
  'longitude' : number,
  'markerType' : { 'coin' : null } |
    { 'monster' : null },
}
export interface Monster {
  'name' : string,
  'energyBoost' : bigint,
  'spawnFrequency' : bigint,
}
export interface PaymentCancelResponse {
  'message' : string,
  'sessionId' : string,
}
export interface PaymentSuccessResponse {
  'message' : string,
  'payment' : {
    'status' : string,
    'paymentMethod' : { 'last4' : string, 'brand' : string },
    'currency' : string,
    'amount' : bigint,
  },
}
export interface PlantedCoin {
  'plantTime' : bigint,
  'owner' : Principal,
  'location' : CoordinatedPoint,
}
export interface PlayerProfile {
  'xp' : bigint,
  'nickname' : string,
  'photoUrl' : [] | [ExternalBlob],
  'level' : bigint,
  'capturedMonsters' : Array<CapturedMonster>,
  'availableTokens' : bigint,
  'plantedTokens' : bigint,
  'bonusTokens' : bigint,
  'registered' : boolean,
  'energy' : bigint,
}
export interface QMYPurchaseRequest {
  'tokensRequested' : bigint,
  'timestamp' : bigint,
  'buyer' : Principal,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'claimWelcomeBonus' : ActorMethod<[], [bigint, bigint]>,
  'getARSpotClaims' : ActorMethod<[], Array<ARSpotClaim>>,
  'getARSpotDistributions' : ActorMethod<[], Array<ARSpotDistribution>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [PlayerProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChatMessages' : ActorMethod<[], Array<ChatMessage>>,
  'getMapMarkers' : ActorMethod<[], Array<MapMarker>>,
  'getPlantedCoins' : ActorMethod<[], Array<PlantedCoin>>,
  'getPlayerByAddress' : ActorMethod<[Principal], [] | [PlayerProfile]>,
  'getPlayerDailyLimits' : ActorMethod<[], DailyLimits>,
  'getQMYPurchaseRequest' : ActorMethod<[], [] | [QMYPurchaseRequest]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [PlayerProfile]>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'paymentCancel' : ActorMethod<[string], PaymentCancelResponse>,
  'paymentSuccess' : ActorMethod<
    [string, string, string],
    PaymentSuccessResponse
  >,
  'saveCallerUserProfile' : ActorMethod<[PlayerProfile], undefined>,
  'sendChatMessage' : ActorMethod<[string], undefined>,
  'submitQMYPurchaseRequest' : ActorMethod<[QMYPurchaseRequest], undefined>,
  'updatePlayerDailyLimits' : ActorMethod<[bigint, bigint], undefined>,
  'updateProfile' : ActorMethod<[string, [] | [ExternalBlob]], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];