/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ARSpotClaim = IDL.Record({
  'claimTime' : IDL.Int,
  'claimedBy' : IDL.Principal,
  'spotId' : IDL.Text,
  'qtmAmount' : IDL.Nat,
});
export const ARSpotDistribution = IDL.Record({
  'totalDistributed' : IDL.Nat,
  'claimCount' : IDL.Nat,
  'spotId' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Monster = IDL.Record({
  'name' : IDL.Text,
  'energyBoost' : IDL.Nat,
  'spawnFrequency' : IDL.Nat,
});
export const CapturedMonster = IDL.Record({
  'monster' : Monster,
  'captureTime' : IDL.Int,
});
export const PlayerProfile = IDL.Record({
  'xp' : IDL.Nat,
  'nickname' : IDL.Text,
  'photoUrl' : IDL.Opt(ExternalBlob),
  'level' : IDL.Nat,
  'capturedMonsters' : IDL.Vec(CapturedMonster),
  'availableTokens' : IDL.Nat,
  'plantedTokens' : IDL.Nat,
  'bonusTokens' : IDL.Nat,
  'registered' : IDL.Bool,
  'energy' : IDL.Nat,
});
export const ChatMessage = IDL.Record({
  'content' : IDL.Text,
  'authorName' : IDL.Text,
  'sender' : IDL.Principal,
  'timestamp' : IDL.Int,
});
export const MapMarker = IDL.Record({
  'id' : IDL.Text,
  'latitude' : IDL.Float64,
  'description' : IDL.Text,
  'longitude' : IDL.Float64,
  'markerType' : IDL.Variant({ 'coin' : IDL.Null, 'monster' : IDL.Null }),
});
export const CoordinatedPoint = IDL.Record({
  'latitude' : IDL.Float64,
  'longitude' : IDL.Float64,
  'address' : IDL.Text,
});
export const PlantedCoin = IDL.Record({
  'plantTime' : IDL.Int,
  'owner' : IDL.Principal,
  'location' : CoordinatedPoint,
});
export const DailyLimits = IDL.Record({
  'rescuesToday' : IDL.Nat,
  'plantsToday' : IDL.Nat,
  'lastResetTime' : IDL.Int,
});
export const QMYPurchaseRequest = IDL.Record({
  'tokensRequested' : IDL.Nat,
  'timestamp' : IDL.Int,
  'buyer' : IDL.Principal,
});
export const PaymentCancelResponse = IDL.Record({
  'message' : IDL.Text,
  'sessionId' : IDL.Text,
});
export const PaymentSuccessResponse = IDL.Record({
  'message' : IDL.Text,
  'payment' : IDL.Record({
    'status' : IDL.Text,
    'paymentMethod' : IDL.Record({ 'last4' : IDL.Text, 'brand' : IDL.Text }),
    'currency' : IDL.Text,
    'amount' : IDL.Nat,
  }),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getARSpotClaims' : IDL.Func([], [IDL.Vec(ARSpotClaim)], ['query']),
  'getARSpotDistributions' : IDL.Func(
      [],
      [IDL.Vec(ARSpotDistribution)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(PlayerProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChatMessages' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
  'getMapMarkers' : IDL.Func([], [IDL.Vec(MapMarker)], ['query']),
  'getPlantedCoins' : IDL.Func([], [IDL.Vec(PlantedCoin)], ['query']),
  'getPlayerByAddress' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(PlayerProfile)],
      ['query'],
    ),
  'getPlayerDailyLimits' : IDL.Func([], [DailyLimits], ['query']),
  'getQMYPurchaseRequest' : IDL.Func(
      [],
      [IDL.Opt(QMYPurchaseRequest)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(PlayerProfile)],
      ['query'],
    ),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'paymentCancel' : IDL.Func([IDL.Text], [PaymentCancelResponse], []),
  'paymentSuccess' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [PaymentSuccessResponse],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([PlayerProfile], [], []),
  'sendChatMessage' : IDL.Func([IDL.Text], [], []),
  'submitQMYPurchaseRequest' : IDL.Func([QMYPurchaseRequest], [], []),
  'updatePlayerDailyLimits' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'updateProfile' : IDL.Func([IDL.Text, IDL.Opt(ExternalBlob)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ARSpotClaim = IDL.Record({
    'claimTime' : IDL.Int,
    'claimedBy' : IDL.Principal,
    'spotId' : IDL.Text,
    'qtmAmount' : IDL.Nat,
  });
  const ARSpotDistribution = IDL.Record({
    'totalDistributed' : IDL.Nat,
    'claimCount' : IDL.Nat,
    'spotId' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Monster = IDL.Record({
    'name' : IDL.Text,
    'energyBoost' : IDL.Nat,
    'spawnFrequency' : IDL.Nat,
  });
  const CapturedMonster = IDL.Record({
    'monster' : Monster,
    'captureTime' : IDL.Int,
  });
  const PlayerProfile = IDL.Record({
    'xp' : IDL.Nat,
    'nickname' : IDL.Text,
    'photoUrl' : IDL.Opt(ExternalBlob),
    'level' : IDL.Nat,
    'capturedMonsters' : IDL.Vec(CapturedMonster),
    'availableTokens' : IDL.Nat,
    'plantedTokens' : IDL.Nat,
    'bonusTokens' : IDL.Nat,
    'registered' : IDL.Bool,
    'energy' : IDL.Nat,
  });
  const ChatMessage = IDL.Record({
    'content' : IDL.Text,
    'authorName' : IDL.Text,
    'sender' : IDL.Principal,
    'timestamp' : IDL.Int,
  });
  const MapMarker = IDL.Record({
    'id' : IDL.Text,
    'latitude' : IDL.Float64,
    'description' : IDL.Text,
    'longitude' : IDL.Float64,
    'markerType' : IDL.Variant({ 'coin' : IDL.Null, 'monster' : IDL.Null }),
  });
  const CoordinatedPoint = IDL.Record({
    'latitude' : IDL.Float64,
    'longitude' : IDL.Float64,
    'address' : IDL.Text,
  });
  const PlantedCoin = IDL.Record({
    'plantTime' : IDL.Int,
    'owner' : IDL.Principal,
    'location' : CoordinatedPoint,
  });
  const DailyLimits = IDL.Record({
    'rescuesToday' : IDL.Nat,
    'plantsToday' : IDL.Nat,
    'lastResetTime' : IDL.Int,
  });
  const QMYPurchaseRequest = IDL.Record({
    'tokensRequested' : IDL.Nat,
    'timestamp' : IDL.Int,
    'buyer' : IDL.Principal,
  });
  const PaymentCancelResponse = IDL.Record({
    'message' : IDL.Text,
    'sessionId' : IDL.Text,
  });
  const PaymentSuccessResponse = IDL.Record({
    'message' : IDL.Text,
    'payment' : IDL.Record({
      'status' : IDL.Text,
      'paymentMethod' : IDL.Record({ 'last4' : IDL.Text, 'brand' : IDL.Text }),
      'currency' : IDL.Text,
      'amount' : IDL.Nat,
    }),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getARSpotClaims' : IDL.Func([], [IDL.Vec(ARSpotClaim)], ['query']),
    'getARSpotDistributions' : IDL.Func(
        [],
        [IDL.Vec(ARSpotDistribution)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(PlayerProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChatMessages' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
    'getMapMarkers' : IDL.Func([], [IDL.Vec(MapMarker)], ['query']),
    'getPlantedCoins' : IDL.Func([], [IDL.Vec(PlantedCoin)], ['query']),
    'getPlayerByAddress' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(PlayerProfile)],
        ['query'],
      ),
    'getPlayerDailyLimits' : IDL.Func([], [DailyLimits], ['query']),
    'getQMYPurchaseRequest' : IDL.Func(
        [],
        [IDL.Opt(QMYPurchaseRequest)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(PlayerProfile)],
        ['query'],
      ),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'paymentCancel' : IDL.Func([IDL.Text], [PaymentCancelResponse], []),
    'paymentSuccess' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [PaymentSuccessResponse],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([PlayerProfile], [], []),
    'sendChatMessage' : IDL.Func([IDL.Text], [], []),
    'submitQMYPurchaseRequest' : IDL.Func([QMYPurchaseRequest], [], []),
    'updatePlayerDailyLimits' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'updateProfile' : IDL.Func([IDL.Text, IDL.Opt(ExternalBlob)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };